# Generated by Django 2.1.7 on 2019-03-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adv_board', '0024_auto_20190327_1405'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advsiteuser',
            name='favored_advs',
            field=models.ManyToManyField(null=True, related_name='favored_by', to='adv_board.Announcement'),
        ),
    ]
