# Generated by Django 2.1.7 on 2019-03-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_advsiteuser_favored_advs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advsiteuser',
            name='favored_advs',
            field=models.ManyToManyField(related_name='favored_by', to='adv_board.Announcement'),
        ),
    ]
