# Generated by Django 2.1.7 on 2019-03-27 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190327_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advsiteuser',
            name='favored_advs',
        ),
    ]
