# Generated by Django 2.1.7 on 2019-03-25 14:25

from django.db import migrations
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('adv_board', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='category',
            field=mptt.fields.TreeManyToManyField(related_name='works', to='adv_board.Category', verbose_name='parent category'),
        ),
    ]
