# Generated by Django 2.1.7 on 2019-03-25 18:49

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('adv_board', '0005_auto_20190325_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adv', to='adv_board.Category', verbose_name='parent category'),
        ),
    ]
