# Generated by Django 2.1.7 on 2019-03-25 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adv_board', '0007_auto_20190325_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='file',
            field=models.FileField(upload_to='files/%Y/%m/%d'),
        ),
    ]
