# Generated by Django 2.1.7 on 2019-03-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adv_board', '0008_auto_20190325_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='file',
            field=models.FileField(blank=True, upload_to='files/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='url',
            field=models.URLField(blank=True, max_length=400),
        ),
    ]
