# Generated by Django 2.1.7 on 2019-03-25 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adv_board', '0009_auto_20190325_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagefile',
            old_name='file',
            new_name='_file',
        ),
    ]
