# Generated by Django 2.1.7 on 2019-03-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adv_board', '0010_auto_20190325_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='_file',
            field=models.ImageField(blank=True, upload_to='files/%Y/%m/%d'),
        ),
    ]
