# Generated by Django 2.1.7 on 2019-03-25 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('adv_board', '0011_auto_20190325_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagePath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=400)),
                ('object_id', models.PositiveIntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='ImageViaFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='files/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='ImageViaUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=400)),
            ],
        ),
        migrations.RemoveField(
            model_name='imagefile',
            name='announcement',
        ),
        migrations.DeleteModel(
            name='ImageFile',
        ),
    ]
