# Generated by Django 2.1.7 on 2019-03-26 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adv_board', '0012_auto_20190325_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagepath',
            name='created_on',
        ),
    ]
