# Generated by Django 2.1.7 on 2019-03-26 00:51

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adv_board', '0013_remove_imagepath_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageviafile',
            name='file',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/photos'), upload_to=''),
        ),
    ]
