# Generated by Django 2.1.7 on 2019-03-26 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adv_board', '0014_auto_20190326_0051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageviafile',
            name='file',
        ),
        migrations.AlterField(
            model_name='imageviaurl',
            name='url',
            field=models.URLField(max_length=150),
        ),
    ]
