# Generated by Django 2.1.7 on 2019-03-26 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adv_board', '0015_auto_20190326_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepath',
            name='path',
            field=models.URLField(max_length=150),
        ),
    ]
