# Generated by Django 2.1.7 on 2019-03-26 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adv_board', '0016_auto_20190326_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepath',
            name='announcement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='adv_board.Announcement'),
            preserve_default=False,
        ),
    ]
