# Generated by Django 2.1.7 on 2019-03-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adv_board', '0017_imagepath_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepath',
            name='path',
            field=models.URLField(blank=True, max_length=150),
        ),
    ]
