# Generated by Django 2.1.7 on 2019-03-26 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adv_board', '0018_auto_20190326_0817'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageViaFile',
        ),
        migrations.DeleteModel(
            name='ImageViaUrl',
        ),
        migrations.RemoveField(
            model_name='imagepath',
            name='announcement',
        ),
        migrations.RemoveField(
            model_name='imagepath',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='imagepath',
            name='object_id',
        ),
        migrations.AddField(
            model_name='announcement',
            name='images',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adv_board.ImagePath'),
            preserve_default=False,
        ),
    ]
