# Generated by Django 2.1.7 on 2019-03-26 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adv_board', '0019_auto_20190326_0918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='images',
        ),
        migrations.AddField(
            model_name='imagepath',
            name='announcement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='adv_board.Announcement'),
            preserve_default=False,
        ),
    ]
