# Generated by Django 2.1.7 on 2019-03-26 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adv_board', '0020_auto_20190326_0921'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='imagepath',
            unique_together={('path', 'announcement')},
        ),
    ]
