# Generated by Django 2.1.7 on 2019-03-26 14:32

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('adv_board', '0021_auto_20190326_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='adv_board.Category', verbose_name='parent category'),
        ),
    ]
