# Generated by Django 2.1.7 on 2019-03-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adv_board', '0023_announcement_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
