# Generated by Django 2.1.7 on 2019-03-27 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adv_board', '0023_advsiteuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advsiteuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='advsiteuser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='AdvSiteUser',
        ),
    ]
