# Generated by Django 2.1.7 on 2019-03-27 20:01

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adv_board', '0024_auto_20190327_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
