# Generated by Django 2.1.7 on 2019-03-27 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adv_board', '0025_advsiteuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advsiteuser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='advsiteuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='advsiteuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='advsiteuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='advsiteuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='advsiteuser',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='advsiteuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='advsiteuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='advsiteuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='advsiteuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='advsiteuser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='advsiteuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='advsiteuser',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='advsiteuser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='advsiteuser',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='advsiteuser',
            name='username',
        ),
    ]
